// This file was generated by ecm_qt_declare_logging_category(): DO NOT EDIT!

#ifndef ECM_QLOGGINGCATEGORY_KCM_MOUSE_LOGGING_H
#define ECM_QLOGGINGCATEGORY_KCM_MOUSE_LOGGING_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(KCM_MOUSE)


#endif
